version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    environment:
      NODE_ENV: development

volumes:
  node_modules:
