name: Code Quality

on:
  push:
    branches-ignore:
      - main
env:
  NEXT_PUBLIC_INTERNAL_API_HOST: ${{ vars.NEXT_PUBLIC_INTERNAL_API_HOST }}
  NEXT_PUBLIC_COMMIT_SHA: ${{ github.sha }}
  NEXT_PUBLIC_LOGFLARE_API_KEY: ${{ secrets.NEXT_PUBLIC_LOGFLARE_API_KEY }}
  NEXT_PUBLIC_LOGFLARE_SOURCE_TOKEN: ${{ secrets.NEXT_PUBLIC_LOGFLARE_SOURCE_TOKEN }}
  NEXT_PUBLIC_VERCEL_ENV: ${{ vars.VERCEL_ENV }}

defaults:
  run:
    shell: bash

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    environment: Preview

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install node@16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Dependencies Audit
        run: npm audit --omit=dev --audit-level=high

      - name: Spellcheck
        run: npm run spellcheck

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test
