name: Vercel Preview Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEXT_PUBLIC_INTERNAL_API_HOST: ${{ vars.NEXT_PUBLIC_INTERNAL_API_HOST }}
  NEXT_PUBLIC_COMMIT_SHA: ${{ github.sha }}
  NEXT_PUBLIC_LOGFLARE_API_KEY: ${{ secrets.NEXT_PUBLIC_LOGFLARE_API_KEY }}
  NEXT_PUBLIC_LOGFLARE_SOURCE_TOKEN: ${{ secrets.NEXT_PUBLIC_LOGFLARE_SOURCE_TOKEN }}

on:
  push:
    branches-ignore:
      - main

  workflow_call:
    inputs:
      DestEnvironment:
        type: string
        description: Destination Environment
        required: true

jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v3

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
